# Generated by Django 4.2.29 on 2026-04-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_add_seller_to_product"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_search__98d711_gin",
        ),
        migrations.RemoveField(
            model_name="product",
            name="search_vector",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
            ),
        ),
    ]
