# Generated by Django 4.2.29 on 2026-04-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_search_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
    ]
